service:
  name: bwb-backend

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-2

functions:
  api:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello
